---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: mysql-${MOLECULE_SCENARIO_NAME}-cluster-01
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 2
    mem: 4
    size: 30G
    groups:
      - mysql_cluster
  - name: mysql-${MOLECULE_SCENARIO_NAME}-cluster-02
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 2
    mem: 4
    size: 30G
    groups:
      - mysql_cluster
  - name: mysql-${MOLECULE_SCENARIO_NAME}-cluster-03
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 2
    mem: 4
    size: 30G
    groups:
      - mysql_cluster
  - name: mysql-${MOLECULE_SCENARIO_NAME}-router-01
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 2
    mem: 4
    size: 30G
    groups:
      - mysql_router
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      allow_world_readable_tmpfiles: true
      callbacks_enabled: ansible.posix.profile_tasks
  playbooks:
    create: ../common/create.yml
    prepare: ../common/prepare.yml
    converge: ../common/install.yml
    side_effect: ../common/install.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
  inventory:
    hosts:
      all:
        libvirt_platforms: "{{ molecule_yml.platforms }}"
        mysql_nolog: false
        mysql_clusteradmin_password: admin
        mysql_cluster_name: molecule
        mysql_router_password: router
        mysql_backup_configure: false
      mysql_cluster:
        mysql_root_password: molecule
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - side_effect
    - verify
