---
- name: Restart master node services
  hosts: mysql
  vars_files:
    - ../../playbooks/vars.yml
  tasks:
    - name: Query cluster status
      community.mysql.mysql_query:
        query: SELECT @@global.super_read_only AS sro
        login_user: "{{ mysql_root_username | default('root') }}"
        login_password: "{{ mysql_root_password }}"
      register: _slave_query

    - name: Stop play for slave nodes
      ansible.builtin.meta: end_host
      when: _slave_query.query_result[0][0]['sro'] ==  1

    - name: Set cluster master facts
      ansible.builtin.set_fact:
        mysql_cluster_master: "{{ inventory_hostname }}"
      loop: "{{ groups[mysql_group | default('mysql')] }}"
      delegate_to: "{{ item }}"
      delegate_facts: true

    - name: Stop MySQL daemon
      ansible.builtin.service:
        name: "{{ mysql_daemon }}"
        state: stopped

    - name: Wait for cluster failover
      ansible.builtin.pause:
        seconds: 30

    - name: Start MySQL daemon
      ansible.builtin.service:
        name: "{{ mysql_daemon }}"
        state: started


- name: Verify cluster failover
  hosts: mysql
  vars_files:
    - ../../playbooks/vars.yml
  tasks:
    - name: Query cluster status
      community.mysql.mysql_query:
        query: SELECT @@global.super_read_only AS sro
        login_user: "{{ mysql_root_username | default('root') }}"
        login_password: "{{ mysql_root_password }}"
      register: _slave_query

    - name: Stop play for slave nodes
      ansible.builtin.meta: end_host
      when: _slave_query.query_result[0][0]['sro'] ==  1

    - name: Verify cluster master failover
      ansible.builtin.assert:
        that: mysql_cluster_master != inventory_hostname


- name: Reset cluster root password
  ansible.builtin.import_playbook: pokerops.mysql.install
  vars:
    mysql_root_password: failover


- name: Verify cluster root password change
  hosts: mysql
  tasks:
    - name: Query cluster status with stored credentials
      ansible.builtin.command:
        cmd: mysql -h '127.0.0.1' -e 'SELECT @@global.super_read_only AS sro'
      register: _slave_cli_query
      retries: 3
      delay: 30
      until: _slave_cli_query is succeeded
      become: true

    - name: Query cluster status with explicit credentials
      community.mysql.mysql_query:
        query: SELECT @@global.super_read_only AS sro
        login_user: root
        login_password: failover
      register: _slave_ansible_query
      retries: 3
      delay: 30
      until: _slave_ansible_query is succeeded
