---
- name: Scale down ClusterSet members
  ansible.builtin.import_playbook: pokerops.mysql.clusterset
  vars:
    mysql_group_prefix: _scaledown
    mysql_cluster_group: mysql_cluster_scaledown

- name: Run verification play for scaledown clusterset
  ansible.builtin.import_playbook: ./verify.yml
  vars:
    mysql_group_prefix: _verify_scaledown
    mysql_cluster_group: mysql_cluster_scaledown
    mysql_verification_clusters:
      - primary
      - secondary

- name: Drop ClusterSet secondary cluster
  ansible.builtin.import_playbook: pokerops.mysql.clusterset
  vars:
    mysql_group_prefix: _drop
    mysql_cluster_group: mysql_cluster_primary

- name: Run verification play ClusterSet cluster removal
  ansible.builtin.import_playbook: ./verify.yml
  vars:
    mysql_group_prefix: _verify_drop
    mysql_cluster_group: mysql_cluster_primary
    mysql_verification_clusters:
      - primary
