---
mysql_secure: true
mysql_manage_config: true
mysql_config_include_files:
  - src: ansible.cnf
    force: yes
  - src: cluster.cnf
    force: yes
mysql_config_overrides: |
  [mysqld]

  max_connections = 512
  general_log = OFF
  general_log_file = /var/log/mysql/mysql.log
  slow_query_log = on
  slow_query_log_file = /var/log/mysql/mysql-slow.log
  log_error = /var/log/mysql/mysql-err.log
  max_binlog_size = 100M
  binlog_expire_logs_seconds = 604800
  relay-log = /var/lib/mysql/relay-bin
  relay-log_index = /var/lib/mysql/relay-bin.index

  innodb_dedicated_server = OFF
  innodb_buffer_pool_size = 8G
  innodb_log_buffer_size = 256M
  innodb_log_file_size = 1G
  innodb_log_files_in_group = 9

mysql_backup_dir: "/backup"
mysql_backup_bin: "/usr/local/bin/mysql-backup"
