---
- name: Verify root password precondition
  ansible.builtin.assert:
    that: mysql_root_password is defined

- name: Verify package preconditions
  ansible.builtin.assert:
    that: mysql_cluster_packages is defined or _packages_versioned | length > 0
  vars:
    _packages: "{{ _mysql_packages }}"
    _packages_versioned: "{{ _packages | select('match', '.*=.*') }}"

- name: Set target package facts
  ansible.builtin.set_fact:
    mysql_cluster_packages: "{{ mysql_packages_default }}"
  when: mysql_cluster_packages is not defined

- name: Debug package targets
  ansible.builtin.debug:
    var: mysql_cluster_packages

- name: Set install facts
  ansible.builtin.set_fact:
    mysql_install_packages: false
    mysql_config_include_files:
      - src: ansible.cnf
        force: yes
      - src: cluster.cnf
        force: yes

- name: Set root password update flag
  ansible.builtin.set_fact:
    mysql_root_password_update: true
  when: mysql_root_password_update is not defined

- name: Query installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Unhold MySQL packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  when: item in packages
  loop: "{{ mysql_cluster_packages | map('split', '=') | map('first') }}"
  changed_when: false

- name: Set MySQL Server package version
  ansible.builtin.set_fact:
    mysql_package_version_installed: "{{ _mysql_version_installed if _mysql_package_query else _mysql_version_target }}"
  vars:
    _mysql_package_query: "{{ mysql_server_package in packages }}"
    _mysql_package: "{{ packages[mysql_server_package] | default([]) }}"
    _mysql_version_installed: "{{ _mysql_package | map(attribute='version') | first }}"
    _mysql_server_package: "{{ mysql_cluster_packages | select('regex', mysql_server_package) }}"
    _mysql_version_target: "{{ _mysql_server_package | map('split', '=') | map('last') | first }}"

- name: Include MySQL variables
  ansible.builtin.include_role:
    name: pokerops.mysql.mysql
    tasks_from: "variables"

- name: Deploy MySQL packages
  ansible.builtin.include_role:
    name: pokerops.mysql.mysql
    tasks_from: "setup-{{ ansible_os_family }}"
  vars:
    mysql_packages: "{{ mysql_cluster_packages }}"

- name: Configure MySQL installation
  ansible.builtin.include_role:
    name: pokerops.mysql.mysql
    tasks_from: "configure"

- name: Manage MySQL deployment
  when: mysql_manage_security | bool
  block:
    - name: Secure MySQL installation
      ansible.builtin.include_role:
        name: pokerops.mysql.mysql
        tasks_from: "secure-installation"

    - name: Manage MySQL clusteradmin user
      community.mysql.mysql_user:
        name: "{{ mysql_clusteradmin_username }}"
        host: "%"
        password: "{{ mysql_clusteradmin_password }}"
        priv: "*.*:ALL,GRANT"
        column_case_sensitive: true
      no_log: "{{ mysql_nolog | default(True) }}"

- name: Hold MySQL packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ mysql_cluster_packages | map('split', '=') | map('first') }}"
  changed_when: false

- name: Query installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Restart MySQL Server
  ansible.builtin.service:
    name: "{{ mysql_server_package }}"
    state: restarted
  vars:
    _mysql_package: "{{ packages[mysql_server_package] }}"
    _mysql_installed_version: "{{ mysql_package_version_installed }}"
    _mysql_installed_target: "{{ _mysql_package | map(attribute='version') | first }}"
  when: _mysql_installed_version != _mysql_installed_target
