---
- name: Configure MySQL backups
  hosts: "{{ mysql_cluster_group | default('mysql_cluster') }}"
  become: true
  vars:
    percona_release: percona-release
  vars_files:
    - ../vars/default.yml
  tasks:
    - name: Query installed packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Install Percona repository
      when: percona_release not in packages
      block:
        - name: Install Percona repository
          ansible.builtin.apt:
            deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb

        - name: Configure Percona repository
          ansible.builtin.command: percona-release enable-only tools release
          changed_when: false

    - name: Create MySQL backup dir
      ansible.builtin.file:
        dest: "{{ _mysql_backup_dir }}"
        state: directory
        mode: "u=rwx,g=rx,o="

    - name: Install Percona XtraBackup
      ansible.builtin.apt:
        name: "{{ _mysql_xtrabackup_package }}"
        update_cache: yes
        state: latest

    - name: Manage DB backup script
      ansible.builtin.template:
        src: backup.j2.sh
        dest: "{{ _mysql_backup_bin }}"
        owner: root
        group: root
        mode: "u=rwx,go=rx"

    - name: Manage DB restore script
      ansible.builtin.template:
        src: restore.j2.sh
        dest: "{{ _mysql_restore_bin }}"
        owner: root
        group: root
        mode: "u=rwx,go=rx"

    - name: Manage DB backup cronjob
      ansible.builtin.cron:
        name: mysql-db-backup
        job: "{{ _mysql_backup_bin }} >/tmp/mysql-db-backup.log 2>&1"
        minute: "{{ _mysql_backup_cron_min }}"
        hour: "{{ _mysql_backup_cron_hour }}"
        weekday: "{{ _mysql_backup_cron_dow }}"

    - name: Create MySQL backup motd pointers
      ansible.builtin.copy:
        dest: /etc/update-motd.d/99-mysql
        content: |
          #!/usr/bin/env bash
          echo run {{ _mysql_backup_bin | basename }} to manually force db backup creation
          echo run {{ _mysql_restore_bin | basename }} to manually force db backup restore
          echo
        mode: "u=rwx,go=rx"
