---
- name: Query MySQL pacakge versions on master nodes
  hosts: "_mysql_master"
  vars_files:
    - vars.yml
  tasks:
    - name: Query package list
      ansible.builtin.package_facts:
        manager: auto

    - name: Query MySQL package targets
      when: mysql_server_package in packages
      block:
        - name: Query installed MySQL server package version
          ansible.builtin.shell:
            cmd: "dpkg -l {{ mysql_server_package }} | awk '{ print $3 }'"
          register: mysql_server_package_query

        - name: Query installed MySQL shell package version
          ansible.builtin.shell:
            cmd: "dpkg -l {{ mysql_shell_package }} | awk '{ print $3 }'"
          register: mysql_shell_package_query

        - name: Set MySQL package facts
          ansible.builtin.set_fact:
            mysql_packages:
              - "{{ mysql_server_package }}={{ mysql_server_package_query }}"
              - "{{ mysql_shell_package }}={{ mysql_shell_package_query }}"

    - name: Bootstrap MySQL package facts
      when: mysql_server_package not in packages
      block:
        - name: Query latest MySQL server package version
          ansible.builtin.shell:
            cmd: "apt-cache madison {{ mysql_server_package }} | awk '{ print $3 }' | grep '^{{ mysql_release }}' | sort -r | head -1"
          register: mysql_server_package_query

        - name: Query installed MySQL shell package version
          ansible.builtin.shell:
            cmd: "apt-cache madison {{ mysql_shell_package }} | awk '{ print $3 }' | sort -r "
          register: mysql_shell_package_query

        - name: Set MySQL package facts
          ansible.builtin.set_fact:
            mysql_packages:
              - "{{ mysql_server_package }}={{ mysql_server_package_query.stdout }}"
              - "{{ mysql_shell_package }}={{ mysql_shell_package_query.stdout }}"

    - debug:
        var: mysql_packages

    - fail:


- name: Deploy MySQL packages on replica nodes
  hosts: "_mysql_slave:_mysql_alien"
  vars_files:
    - vars.yml
  vars:
    mysql_alien: "{{ inventory_hostname in groups['_mysql_alien'] }}"
    mysql_manage_config: true
    mysql_manage_replication: false
    mysql_manage_security: "{{ mysql_alien | bool }}"
    mysql_manage_dbs: "{{ mysql_alien | bool }}"
    mysql_manage_users: "{{ mysql_alien | bool }}"
    mysql_cluster_user: clusteradmin
  tasks:
    - name: Query package list
      ansible.builtin.package_facts:
        manager: auto

    - name: Unhold MySQL packages
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: install
      when: item in packages
      loop: "{{ mysql_packages }}"
      changed_when: false

    - name: Deploy MySQL packages
      ansible.builtin.include_role:
        name: geerlingguy.mysql

    - name: Hold MySQL packages
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ mysql_packages }}"
      changed_when: false
