---
- name: Deploy MySQL repository
  hosts: "_mysql_master:_mysql_slave:_mysql_alien:{{ mysql_router_group | default('mysql_router') }}"
  become: true
  any_errors_fatal: true
  vars_files:
    - vars.yml
  tasks:
    - name: Verify mysql variable definitions
      ansible.builtin.assert:
        that:
          - mysql_root_password is defined
          - mysql_clusteradmin_password is defined
        fail_msg: "mysql_root_password and mysql_clusteradmin_password must be defined"

    - name: Add host entries for cluster members
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}.*"
        line: "{{ _member_address }} {{ _fqdn }} {{ _hostname }}"
      vars:
        _member_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        _fqdn: "{{ hostvars[item]['ansible_fqdn'] }}"
        _hostname: "{{ hostvars[item]['ansible_hostname'] }}"
      loop: "{{ ansible_play_hosts }}"
      when: mysql_config_hostnames | default(True) | bool

    - name: Check package pins
      ansible.builtin.assert:
        that: mysql_shell_package is not search('=')
        fail_msg: "Playbook does not support mysql_shell package pinning, got {{ mysql_shell_package }}"

    - name: Configure MySQL repo
      ansible.builtin.include_role:
        name: pokerops.mysql.repo
