---
# Hardcoded values
mysql_root_username: root
mysql_root_home: "~{{ mysql_root_username }}"
mysqlsh_configdir: "~/.mysqlsh"
mysql_daemon: mysql
mysql_clusteradmin_username: clusteradmin
mysql_server_package: "mysql-server"
mysql_client_package: "mysql-client"
mysql_shell_package: "mysql-shell"
mysql_hostgroups:
  - _mysql_master
  - _mysql_slave
  - _mysql_alien

# Overridable parameters
_mysql_config_hostnames: "{{ mysql_config_hostnames | default(True) }}"
