---
name: libvirt

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    strategy:
      matrix:
        scenario:
          - install
          - failover
          - scaleup
          - scaledown
          - xtrabackup
          - mysqldump
          - update
          - clusterset
        image:
          - distro: jammy
            url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
          - distro: noble
            url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    env:
      MOLECULE_LOGDIR: "/tmp/logs"
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: |
            make requirements test \
            MOLECULE_SCENARIO=${{ matrix.scenario }} \
            MOLECULE_KVM_DISTRO=${{ matrix.image.distro }} \
            MOLECULE_KVM_IMAGE=${{ matrix.image.url }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.image.distro }}
          path: |
            ${{ env.MOLECULE_LOGDIR }}/*.log
          if-no-files-found: ignore
        if: always()
